### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by adamperkowski** [Hejsil/dipm#24]
hey. in the README you've mentioned that you love Arch Linux. well, i'd be happy to package dipm for Arch... BUT building fails on master (99b92bac8ab195153b36bd399e3e27b39ae4c8ec). i don't know, i might be doing something wrong. i'm not a zig expert.
```text
install
└─ install dipm
   └─ zig build-exe dipm Debug native 6 errors
src/PackageManager.zig:180:51: error: no field named 'fn' in union 'builtin.Type'
    @typeInfo(@TypeOf(downloadAndExtractPackage)).@"fn".return_type.?;
                                                  ^~~~~
/usr/lib/zig/std/builtin.zig:256:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
referenced by:
    DownloadAndExtractJob: src/PackageManager.zig:538:13
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
src/Diagnostics.zig:63:59: error: no field named 'struct' in union 'builtin.Type'
    inline for (@typeInfo(@TypeOf(diagnostics.successes)).@"struct".fields) |field|
                                                          ^~~~~~~~~
/usr/lib/zig/std/builtin.zig:256:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
src/Diagnostics.zig:276:58: error: no field named 'struct' in union 'builtin.Type'
    inline for (@typeInfo(@TypeOf(diagnostics.failures)).@"struct".fields) |field| {
                                                         ^~~~~~~~~
/usr/lib/zig/std/builtin.zig:256:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
src/fs.zig:245:24: error: root struct of file 'fs.Dir' has no member named 'OpenOptions'
        dir: std.fs.Dir.OpenOptions = .{},
             ~~~~~~~~~~^~~~~~~~~~~~
/usr/lib/zig/std/fs/Dir.zig:1:1: note: struct declared here
fd: posix.fd_t,
^~
/usr/lib/zig/std/meta.zig:29:51: error: value stored in comptime field does not match the default value of the field
                kvs_array[i] = .{ enumField.name, @field(T, enumField.name) };
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
src/Progress.zig:177:10: error: no field named 'row' in struct 'os.linux.winsize'
        .row = 0,
         ^~~
/usr/lib/zig/std/os/linux.zig:4287:28: note: struct declared here
pub const winsize = extern struct {
                    ~~~~~~~^~~~~~
```

**Comment by Hejsil** [comment]
dipm is built with a build of zigs master branch. I see that might be an issue if you want to build it with the version of zig in the arch package repositiory.

**Comment by adamperkowski** [comment]
oh okay. might be worth mentioning in the readme. any specific commit or just master?

**Comment by Hejsil** [comment]
> any specific commit or just master?

Well, i always have a recent version of zig master on hand, so there is no specific commit.

**Comment by Hejsil** [comment]
`dipm` now builds with 0.14.0 and will have the minimum zig version specified in `build.zig.zon`

https://github.com/Hejsil/dipm/blob/master/build.zig.zon#L4
